### ISSUE TITLE
强势围观米神CompanionsPlus

### ISSUE THREAD

**Issue by sumdream** [handy-git/CompanionsPlus#1]
<img width="362" alt="QQ图片20240226205726" src="https://github.com/handy-git/CompanionsPlus/assets/8602256/0abff22e-87e5-4514-990c-846d6ac145a1">

![QQ图片20240226205734](https://github.com/handy-git/CompanionsPlus/assets/8602256/4169df0f-4914-4ec3-b947-25876c1031f8)

![QQ图片20240226205749](https://github.com/handy-git/CompanionsPlus/assets/8602256/2658cc97-343c-44b6-80cc-9e52134f212f)

![QQ图片20240226205758](https://github.com/handy-git/CompanionsPlus/assets/8602256/eb4b78f1-9293-41c2-afc1-238ee42e22c8)
<img width="348" alt="QQ图片20240226205815" src="https://github.com/handy-git/CompanionsPlus/assets/8602256/35d2cbca-612f-49c6-a218-0849d3608d0e">

![Snipaste_2024-02-26_20-56-49](https://github.com/handy-git/CompanionsPlus/assets/8602256/f97250dc-ef51-4255-9642-cb88e7c3e9a7)

![Snipaste_2024-02-26_20-56-58](https://github.com/handy-git/CompanionsPlus/assets/8602256/ab6d33c4-b5a2-4a40-b55b-3eac43e06c76)

**Comment by meteorOSS** [comment]
我米圣这就从零开始耗时九个月研发 issue删除
